### ISSUE TITLE
Problem with the mdns and webserver

### ISSUE THREAD

**Issue by ktlk21** [1024kilobyte/CoffeePID#2]
i only can visit the page with ip address..the http://coffeepid.local/ does not work...that ok..no problem
the problem is when i visit with ip the page is like that...and whatever click ,in browser address bar there is change but exactly the same image
![image](https://user-images.githubusercontent.com/76667611/110825679-fb721980-829c-11eb-8f5a-7ad64dfc6c40.png)

**Comment by 1024kilobyte** [comment]
Please check if your network supports mDNS requests. If another device in the same network cannot ping the coffeePID ("ping coffeepid.local" should work), you should take a look at your network first. I actually had to make changes to my network, which were adding the hostname "coffeepid.local" to the exceptions for DNS-Rebind-Protection. Else DNS requests for devices in the same network will be blocked by my Router / Accesspoint (FritzBox 7490).

**Comment by ktlk21** [comment]
Ok the problem was with windows..does not support mDNS ..i found a solution and in windows laptop is ok...My android phone doesn't support mdns so its ok,
The problem now is that the site is not load probably ,,like something is missing...
![image](https://user-images.githubusercontent.com/76667611/110836303-8efd1780-82a8-11eb-8792-ba16bf8b7b1d.png)
![image](https://user-images.githubusercontent.com/76667611/110836335-98867f80-82a8-11eb-8776-0a53cec3ac51.png)
![image](https://user-images.githubusercontent.com/76667611/110836385-a4724180-82a8-11eb-883a-c74b09829fd5.png)

**Comment by 1024kilobyte** [comment]
To find the cause for issues like that, I recommend opening the website in Chrome (with Developer Tools active) and check the Console. Please share any error messages appearing.

**Comment by ktlk21** [comment]
![image](https://user-images.githubusercontent.com/76667611/110850817-e86d4280-82b8-11eb-87c5-a6a36c3189e3.png)

**Comment by ktlk21** [comment]
the log from littlefs upload
[LittleFS] data    : C:\Users\ktlk\Documents\Arduino\CoffeePID\data
[LittleFS] size    : 14312
[LittleFS] page    : 256
[LittleFS] block   : 8192
/config.json
/www/app.html.gz
/www/css/app.css
/www/css/app.opt.css
/www/css/app.opt.css.gz
/www/css/bs4.min.css
/www/css/bs4.opt.css
/www/css/bs4.opt.css.gz
/www/favicon.ico.gz
/www/home.html.gz
/www/img/app-icon.png.gz
/www/img/app.html
/www/img/bg.jpg
/www/img/bg.jpg.gz
/www/img/cog.svg
/www/img/cog.svg.gz
/www/img/info.svg
/www/img/info.svg.gz
/www/img/lock.svg
/www/img/lock.svg.gz
/www/img/mug-hot.svg
/www/img/mug-hot.svg.gz
/www/img/router.svg
/www/img/router.svg.gz
/www/img/thermo.svg
/www/img/thermo.svg.gz
/www/img/water-temp.svg
/www/img/water-temp.svg.gz
/www/img/wifi.svg
/www/img/wifi.svg.gz
/www/js/app.js
/www/js/app.min.js.gz
/www/js/bs-input.min.js
/www/js/bs-input.min.js.gz
/www/js/bs4.bundle.min.js
/www/js/bs4.bundle.min.js.gz
/www/js/content.js.gz
/www/js/jq.min.js
/www/js/jq.min.js.gz
/www/js/vendor.min.js
/www/js/vendor.min.js.gz
/www/settings.html.gz
[LittleFS] upload  : C:\Users\ktlk\AppData\Local\Temp\arduino_build_353325/CoffeePID.mklittlefs.bin
[LittleFS] address : 0x200000
[LittleFS] reset   : --before default_reset --after hard_reset
[LittleFS] port    : COM3
[LittleFS] speed   : 115200
[LittleFS] python   : C:\Users\ktlk\AppData\Local\Arduino15\packages\esp8266\tools\python3\3.7.2-post1\python3.exe
[LittleFS] uploader : C:\Users\ktlk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\tools\upload.py

esptool.py v2.8
Serial port COM3
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: e8:68:e7:80:9d:d9
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 16MB
Compressed 14655488 bytes to 443036...
Wrote 14655488 bytes (443036 compressed) at 0x00200000 in 104.3 seconds (effective 1123.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

**Comment by ktlk21** [comment]
and log from sketch upload

Executable segment sizes:
IROM   : 329188          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 28040   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1284  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 3080  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 26200 )         - zeroed variables      (global, static) in RAM/HEAP 
Sketch uses 361592 bytes (34%) of program storage space. Maximum is 1044464 bytes.
Global variables use 30564 bytes (37%) of dynamic memory, leaving 51356 bytes for local variables. Maximum is 81920 bytes.
esptool.py v2.8
Serial port COM3
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: e8:68:e7:80:9d:d9
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 16MB
Compressed 365744 bytes to 263644...
Wrote 365744 bytes (263644 compressed) at 0x00000000 in 23.4 seconds (effective 124.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

**Comment by 1024kilobyte** [comment]
I'm not familiar with the Edge Developer Tools, but is there also a Network Tab, were you can see the network requests sent. Maybe there is something wrong with the urls...

**Comment by ktlk21** [comment]
![image](https://user-images.githubusercontent.com/76667611/110912404-9100be00-831c-11eb-979b-a2a5985ce777.png)
file not found
how i can see the files in littleFS in wedos?

**Comment by ktlk21** [comment]
When i visit the site with ip from my phone it shows the image with the mug and the cog..in pc not

**Comment by ktlk21** [comment]
Everything OK.. the problem was edge (both on pc and phone).. i tried dolphin with ios agent but the same. With chrome i just test and everything OK... thank you so much for the support.. you are awesome
