### ISSUE TITLE
wifi not working 

### ISSUE THREAD

**Issue by ktlk21** [1024kilobyte/CoffeePID#4]
when I test the code with out ssr everything works fine, even if I connect the ssr after power on the machine everything fine 
when i connect ssr and  power on the machine  the WiFi not working.. no ssid emit.. even if disconnect the ssr no WiFi emit...

**Comment by 1024kilobyte** [comment]
Is the SSR open or closed while powered off? It sounds as if your ESP is not booting up correctly, maybe due to power issues. What does the serial monitor say?

**Comment by ktlk21** [comment]
when i power from usb everything is OK.. when I power from 5v on the board then i have issues.. the ssr light is on when i power on..

**Comment by 1024kilobyte** [comment]
Still sounds like an issue regarding the power supply. Which power brick do you use and how is it connected to the coffee machine and the ESP?

**Comment by ktlk21** [comment]
i use this https://www.skroutz.gr/s/16470175/%CE%A4%CF%81%CE%BF%CF%86%CE%BF%CE%B4%CE%BF%CF%84%CE%B9%CE%BA%CF%8C-PCB-3-3V-8-25W-2-5A-MeanWell-IRM-10-3-3.html
but OK..i power from USB the wemos and the max31685 from meanwell.. everything works fine now
